Repository airbus/scikit-decide, pull requests merged in 2023-09, with the labels that each got.

#266 Aiplan4eu up bridge
  examples/up_bridge.py
  pyproject.toml
  skdecide/hub/domain/up/__init__.py
  skdecide/hub/domain/up/up.py
  skdecide/hub/solver/up/__init__.py
  skdecide/hub/solver/up/up.py
  tests/domains/python/test_up_bridge_domain.py
  tests/solvers/python/test_up_bridge_solver.py
Labels: enhancement

#269 Downgrade entry_points to enable gym import
  .github/workflows/build.yml
  docs/install.md
Labels: bug, ci/cd

#205 Change way action space is discretized
  skdecide/hub/domain/gym/gym.py
Labels: bug

#270 Synchronize package dependencies between build.yml and release.yml
  .github/workflows/release.yml
Labels: bug, ci/cd

#271 Remove deprecated mybinder federations and update the gesis one
  .github/workflows/release.yml
Labels: bug, ci/cd
