Repository airbus/scikit-decide, pull requests merged in 2024-04, with the labels that each got.

#325 Update to latest UP version
  pyproject.toml
Labels: enhancement

#322 Remove pattern try...except from tests
  tests/solvers/cpp/test_cpp_solvers.py
  tests/solvers/python/test_python_solvers.py
  tests/solvers/python/test_up_bridge_solver.py
Labels: enhancement

#328 poll schumann + plots + tests
  notebooks/15_flightplanning_tuto.ipynb
  skdecide/hub/domain/flight_planning/aircraft_performance/__init__.py
  skdecide/hub/domain/flight_planning/aircraft_performance/base.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/__init__.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/data/aircraft_engine_params.csv
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/engine_loader.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/__init__.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/aircraft_parameters.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/atmospheric_parameters.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/constants.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/jet.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/operational_limits.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/parameters/units.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/pollschumann.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/utils/__init__.py
  skdecide/hub/domain/flight_planning/aircraft_performance/poll_schumann_utils/utils/aero.py
  skdecide/hub/domain/flight_planning/domain.py
  skdecide/hub/domain/flight_planning/flightplanning_utils.py
  skdecide/hub/domain/flight_planning/weather_interpolator/weather_tools/get_weather_noaa.py
  skdecide/hub/domain/flight_planning/weather_interpolator/weather_tools/interpolator/GenericInterpolator.py
  skdecide/hub/domain/flight_planning/weather_interpolator/weather_tools/interpolator/WeatherInterpolator.py
  skdecide/hub/domain/flight_planning/weather_interpolator/weather_tools/parser_pygrib.py
  skdecide/hub/domain/flight_planning/weather_interpolator/weather_tools/unit_conversion.py
  tests/flight_planning/aircraft_performance/test_aircraft_perf_model.py
  tests/flight_planning/aircraft_performance/test_poll_schumann.py
Labels: enhancement

#329 Update MacOS known issues in the install docs
  docs/install.md
Labels: documentation

#331 Use macos-12 instead of macos-latest to build wheels
  .github/workflows/build.yml
  .github/workflows/release.yml
Labels: bug, enhancement

#327 Add getters for the computed plan or policy computed by each solver
  skdecide/hub/solver/ilaostar/ilaostar.py
  skdecide/hub/solver/lazy_astar/lazy_astar.py
  skdecide/hub/solver/lrtastar/lrtastar.py
  skdecide/hub/solver/lrtdp/lrtdp.py
  skdecide/hub/solver/martdp/martdp.py
  skdecide/hub/solver/mcts/mcts.py
  skdecide/hub/solver/ray_rllib/ray_rllib.py
  skdecide/hub/solver/riw/riw.py
  skdecide/hub/solver/stable_baselines/stable_baselines.py
  skdecide/hub/solver/up/up.py
  tests/solvers/python/test_python_solvers.py
  tests/solvers/python/test_ray_rllib.py
  tests/solvers/python/test_up_bridge_solver.py
Labels: bug, enhancement

#343 Correct moving average epsilons in C++ rollout-based algorithms
  cpp/src/hub/solver/lrtdp/impl/lrtdp_impl.hh
  cpp/src/hub/solver/lrtdp/lrtdp.hh
  cpp/src/hub/solver/martdp/impl/martdp_impl.hh
  cpp/src/hub/solver/mcts/impl/mcts_impl.hh
  cpp/src/hub/solver/riw/impl/riw_impl.hh
Labels: bug

#344 Fix versions drop-list in deployed doc
  package.json
  yarn.lock
Labels: bug
