Repository airbus/scikit-decide, pull requests merged in 2024-05, with the labels that each got.

#330 Integrate binder environment in development branches instead of a separate dedicated orphan branch
  .github/workflows/build-doc.yml
  .github/workflows/build.yml
  .github/workflows/deploy-doc.yml
  .github/workflows/release.yml
  binder/apt.txt
  binder/environment.yml
  binder/install_nightly_build.py
  binder/postBuild
  binder/start
  docs/autodoc.py
  docs/notebooks/README.template.md
Labels: enhancement

#347 Update code for rllib>=2.20
  poetry.lock
  skdecide/hub/solver/ray_rllib/ray_rllib.py
  tests/solvers/python/test_ray_rllib.py
Labels: bug

#361 Implement callbacks for python solvers
  skdecide/hub/solver/ars/ars.py
  skdecide/hub/solver/cgp/cgp.py
  skdecide/hub/solver/cgp/pycgp/cgpes.py
  skdecide/hub/solver/do_solver/do_solver_scheduling.py
  skdecide/hub/solver/lazy_astar/lazy_astar.py
  skdecide/hub/solver/lrtastar/lrtastar.py
  skdecide/hub/solver/maxent_irl/maxent_irl.py
  skdecide/hub/solver/pomcp/pomcp.py
  skdecide/hub/solver/stable_baselines/stable_baselines.py
  tests/solvers/python/test_python_solvers.py
Labels: enhancement

#364 Replace `Domain.solve_with()` by direct usage of `solver.solve()` and `solver.load()`
  docs/guide/README.md
  examples/ars_solver.py
  examples/baselines_solver.py
  examples/cgp_solver.py
  examples/full_multisolve.py
  examples/grid_mdp_multisolve.py
  examples/grid_multisolve.py
  examples/gym_jsbsim_greedy.py
  examples/gym_jsbsim_iw.py
  examples/gym_jsbsim_riw.py
  examples/gym_jsbsim_uct.py
  examples/gym_line_control.py
  examples/maxent_irl_solver.py
  examples/maze_multiagent_mdp_multisolve.py
  examples/nocycle_grid_goal_mdp.py
  examples/rllib_solver_applicable_actions.py
  examples/rllib_solver_gym_domain.py
  examples/rllib_solver_skdecide_domain.py
  examples/tutorial.py
  examples/up_native_solvers.py
  examples/up_skdecide_solvers.py
  notebooks/11_maze_tuto.ipynb
  notebooks/12_gym_tuto.ipynb
  notebooks/14_benchmarking_tuto.ipynb
  notebooks/15_flightplanning_tuto.ipynb
  skdecide/builders/solver/fromanystatesolvability.py
  skdecide/builders/solver/restorability.py
  skdecide/domains.py
  skdecide/hub/domain/flight_planning/domain.py
  skdecide/hub/solver/mahd/mahd.py
  skdecide/hub/solver/pomcp/pomcp.py
  skdecide/solvers.py
  tests/domains/python/test_up_bridge_domain.py
  tests/domains/test_gym.py
  tests/flight_planning/test_flight_planning.py
  tests/solvers/cpp/parallelism/test_parallel_deterministic_algorithms.py
  tests/solvers/cpp/parallelism/test_parallel_probabilistic_algorithms.py
  tests/solvers/cpp/test_cpp_solvers.py
  tests/solvers/python/test_python_solvers.py
  tests/solvers/python/test_ray_rllib.py
  tests/solvers/python/test_up_bridge_solver.py
Labels: enhancement

#367 Unify the rollout utilities
  examples/scheduling/computation_time_experiments.py
  examples/scheduling/gphh_example.py
  examples/scheduling/rcpsp_examples.py
  examples/scheduling/toy_rcpsp_examples.py
  notebooks/13_scheduling_tuto.ipynb
  skdecide/hub/solver/do_solver/gphh.py
  skdecide/hub/solver/meta_policy_scheduling/meta_policies.py
  skdecide/utils.py
  tests/scheduling/test_scheduling.py
Labels: bug, enhancement

#375 Implement callback for mahd solver
  skdecide/hub/solver/mahd/mahd.py
Labels: enhancement

#384 Update openap version
  poetry.lock
  pyproject.toml
  tests/flight_planning/test_flight_planning.py
Labels: dependencies

#386 Correct bug RayRLlib filtered action Torch model
  skdecide/hub/solver/ray_rllib/custom_models.py
Labels: bug

#389 Correct bug when dealing with dictionary spaces in Gym domain's BEE features
  skdecide/hub/domain/gym/gym.py
Labels: bug

#390 Correct bug in UP when converting back states to SkUPStates
  skdecide/hub/domain/up/up.py
Labels: bug
