Repository airbus/scikit-decide, pull requests merged in 2024-01, with the labels that each got.

#308 Homogenise and debug RL solvers and implement action masking in RLlib
  examples/rllib_solver_applicable_actions.py
  examples/rllib_solver_gym_domain.py
  examples/rllib_solver_skdecide_domain.py
  notebooks/11_maze_tuto.ipynb
  skdecide/hub/domain/gym/gym.py
  skdecide/hub/domain/mastermind/mastermind.py
  skdecide/hub/domain/maze/maze.py
  skdecide/hub/domain/simple_grid_world/simple_grid_world.py
  skdecide/hub/solver/ray_rllib/custom_models.py
  skdecide/hub/solver/ray_rllib/ray_rllib.py
  skdecide/hub/solver/stable_baselines/stable_baselines.py
  skdecide/hub/space/gym/__init__.py
  skdecide/hub/space/gym/gym.py
  tests/solvers/python/test_python_solvers.py
  tests/solvers/python/test_ray_rllib.py
Labels: bug, enhancement, python

#309 Improve unified planning support
  examples/car_nodrag.pddl
  examples/up_native_solvers.py
  examples/up_skdecide_solvers.py
  pyproject.toml
  skdecide/hub/domain/flight_planning/__init__.py
  skdecide/hub/domain/rcpsp/__init__.py
  skdecide/hub/domain/up/up.py
  skdecide/hub/solver/do_solver/__init__.py
  skdecide/hub/solver/gphh/__init__.py
  skdecide/hub/solver/meta_policy/__init__.py
  skdecide/hub/solver/pile_policy/__init__.py
  skdecide/hub/solver/ray_rllib/ray_rllib.py
  skdecide/hub/solver/sgs_policies/__init__.py
  skdecide/hub/space/gym/gym.py
  tests/domains/python/test_up_bridge_domain.py
  tests/solvers/python/test_up_bridge_solver.py
Labels: enhancement

#310 Enable dynamic-versioning using poetry-dynamic-versioning
  pyproject.toml
  skdecide/__init__.py
Labels: bug, enhancement
